src/Web/Models/EmailDto.cs
namespace Web.Models
{
    public class EmailDto
    {
        public string Email { get; set; }
    }
}

src/Web/Models/GeoIpDto.cs
namespace Web.Models
{
    public class GeoIpDto
    {
        public string ip { get; set; }
        public string country_code { get; set; }
        public string region_code { get; set; }
        public string city { get; set; }
        public string zip_code { get; set; }
    }
}

src/Web/Controllers/Api/SubscriberController.cs
using Microsoft.AspNetCore.Mvc;
using Web.Models;
using Web.Data;
using Web.Providers;
using Data;
using Microsoft.Extensions.Logging;
using System;

// For more information on enabling Web API for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace Web.Controllers
{
    [Route("api/[controller]")]
    public class SubscriberController : Controller
    {
        private readonly IRepository<SubscriberEntity, string> _subscriberRepository;
        private readonly LocationProvider _locationProvider;
        private readonly ILogger<SubscriberController> _logger;

        public SubscriberController(IRepository<SubscriberEntity, string> subscriberRepository, LocationProvider locationProvider, ILogger<SubscriberController> logger)
        {
            _subscriberRepository = subscriberRepository;
            _locationProvider = locationProvider;
            _logger = logger;
        }

        // POST api/values
        [HttpPost, ValidateAntiForgeryToken]
        public IActionResult Post([FromBody]EmailDto email)
        {
            if (email == null || string.IsNullOrEmpty(email.Email))
            {
                return BadRequest();
            }

            try
            {
                var remoteIpAddress = Request.Headers["IpAddress"];
                var location = _locationProvider.GetLocation(remoteIpAddress);

                var newSubscriber = new SubscriberEntity(email.Email.ToLower(), location.country_code)
                {
                    IpAddress = remoteIpAddress,
                    CountryCode = location.country_code,
                    RegionCode = location.region_code,
                    City = location.city,
                    ZipCode = location.zip_code
                };

                _subscriberRepository.Upsert(email.Email, newSubscriber);

                return Ok();
            }
            catch (Exception ex)
            {
                return StatusCode(500, ex);
            }
        }
    }
}

src/Web/Controllers/Api/VendorController.cs
using System;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json.Linq;
using Web.Providers;
using Web.Data;
using Microsoft.Extensions.Logging;
using Data;

// For more information on enabling Web API for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace Web.Controllers.Api
{
    [Route("api/[controller]")]
    public class VendorController : Controller
    {
        private readonly IRepository<VendorEntity, string> _vendorRepository;
        private readonly LocationProvider _locationProvider;
        private readonly ILogger<VendorController> _logger;

        public VendorController(IRepository<VendorEntity, string> vendorRepository, LocationProvider locationProvider, ILogger<VendorController> logger)
        {
            _vendorRepository = vendorRepository;
            _locationProvider = locationProvider;
            _logger = logger;
        }

        [HttpGet, ValidateAntiForgeryToken]
        [Route("unique/{email}")]
        public IActionResult Unique(string email)
        {
            if (string.IsNullOrEmpty(email))
            {
                return BadRequest();
            }

            try
            {
                VendorEntity vendor;
                bool isUnique = !_vendorRepository.TryGet(email.ToLower(), out vendor);

                return new ObjectResult(new { isUnique = isUnique });
            }
            catch (Exception ex)
            {
                return StatusCode(500, ex);
            }
        }

        // POST api/values
        [HttpPost, ValidateAntiForgeryToken]
        public IActionResult Post([FromBody]JObject formData)
        {
            try
            {
                var remoteIpAddress = Request.Headers["IpAddress"];
                var location = _locationProvider.GetLocation(remoteIpAddress);

                var emailToken = formData["email"]?.ElementAtOrDefault(0);
                var firstNameToken = formData["fullname"]?.ElementAtOrDefault(0);
                var lastNameToken = formData["fullname"]?.ElementAtOrDefault(1);
                var hourlyRateToken = formData["hourlyRate"]?.ElementAtOrDefault(0);
                var isFreelancerToken = formData["isFreelancer"]?.ElementAtOrDefault(0);
                var servicesOfferedToken = formData["servicesOffered"];
                var wantsToBlogToken = formData["wantsToBlog"]?.ElementAtOrDefault(0);
                var firmNameToken = formData["firmName"]?.ElementAtOrDefault(0);
                var firmFoundedToken = formData["firmFounded"]?.ElementAtOrDefault(0);

                var email = emailToken.Value<string>();

                if (emailToken == null || isFreelancerToken == null || wantsToBlogToken == null || servicesOfferedToken == null)
                {
                    return BadRequest();
                }

                var isFreelancer = isFreelancerToken.Value<string>().Equals("freelancer", StringComparison.CurrentCultureIgnoreCase) ? true : false;
                var wantsToBlog = wantsToBlogToken.Value<string>().Equals("Yes", StringComparison.CurrentCultureIgnoreCase) ? true : false;
                var servicesOffered = (JArray)servicesOfferedToken;
                var services = servicesOffered.Select(s => (string)s).ToList();

                var vendorEntity = new VendorEntity(email.ToLower(), location.country_code)
                {
                    FirstName = firstNameToken?.Value<string>(),
                    LastName = lastNameToken?.Value<string>(),
                    CompanyName = firmNameToken?.Value<string>(),
                    CompanyFounded = firmFoundedToken?.Value<int>() ?? 0,
                    IsFreelancer = isFreelancer,
                    WantsToBlog = wantsToBlog,
                    HourlyRate = hourlyRateToken?.Value<decimal>() ?? 0,
                    Services = services,
                    IpAddress = remoteIpAddress,
                    CountryCode = location.country_code,
                    RegionCode = location.region_code,
                    City = location.city,
                    ZipCode = location.zip_code
                };

                _vendorRepository.Create(vendorEntity);

                return Ok();
            }
            catch (Exception ex)
            {
                _logger.LogError(new EventId(500, "Internal Server Error"), ex, ex.Message);
                return StatusCode(500, ex);
            }
        }
    }
}

src/Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace Web.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Error()
        {
            return View();
        }
    }
}

src/Web/Controllers/VendorController.cs
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace Web.Controllers
{
    public class VendorController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }
    }
}

src/Web/Views/Home/Index.cshtml
@{
    var request = ViewContext.HttpContext.Request;
    var routeUrl = Url.RouteUrl(ViewContext.RouteData.Values);
    var thisUrl = $"{request.Scheme}://{request.Host}{routeUrl}";

    var facebookShareUrl = $"http://www.facebook.com/sharer/sharer.php?u={thisUrl}";
}

@section metatags
{
    <meta property="og:url" content="@thisUrl" />
    <meta property="og:type" content="website" />
    <meta property="og:title" content="Information is power" />
    <meta property="og:description" content="Learn how much your business should really pay for services. Find the best vendors. Simple. Sign up for updates, sneak peeks, and special offers as we build a better way to buy business services." />
}

@section navbar
{
    <nav class="navbar navbar-transparent navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="@Url.Action("Index", "Home")"><img src="~/images/logo.small.png" /></a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="@Url.Action("Index", "Vendor")">
                            <i class="fa fa-users" aria-hidden="true"></i>
                            Vendor Application
                        </a>
                    </li>
                    <li>
                        <a href="@facebookShareUrl">
                            <i class="fa fa-facebook-square"></i>
                            Share
                        </a>
                    </li>
                    <li>
                        <a href="mailto:info@lumaven.com">
                            <i class="fa fa-envelope-o"></i>
                            Contact Us
                        </a>
                    </li>
                </ul>

            </div><!-- /.navbar-collapse -->
        </div><!-- /.container -->
    </nav>    
}

<div class="background-white-frosted"></div>
<md-content ng-controller="HomeController as ctrl" 
            style="background: none;"
            ng-cloak
            flex>
    @Html.AntiForgeryToken()
    <div class="container">
        <div class="cover-container">
            <div class="inner cover">
                <h1 class="cover-heading">Coming soon</h1>
                <p class="lead"><h3>Information is power. Learn how much your business should really pay for services. Find the best vendors. Simple.</h3></p>
                <p class="lead">
                    <h4>Sign up for updates, sneak peeks, and special offers as we build a better way to buy business services.</h4>
                    <form name="notifyMe"
                          class="form-inline"
                          role="form"
                          novalidate
                          layout="column"
                          layout-align="center center">
                        <div layout="row"
                             layout-xs="column">
                            <md-input-container class="md-block"
                                                ng-if="!ctrl.success">
                                <label>Email</label>
                                <md-icon>email</md-icon>
                                <input type="email"
                                       ng-model="ctrl.email"
                                       name="email"
                                       ng-pattern="@Html.Raw("/^.+@.+\\..+$/")">
                                <div ng-messages="notifyMe.email.$error"
                                     ng-if="notifyMe.email.$touched && notifyMe.email.$dirty && notifyMe.email.$invalid">
                                    <div ng-message-exp="['required', 'pattern']">
                                        Your email must look like an email address.
                                    </div>
                                </div>
                            </md-input-container>
                            <div class="md-block"
                                 style="margin-top: 9px;"
                                 ng-if="!ctrl.success">
                                <md-button type="submit"
                                           class="md-primary md-raised"
                                           ng-click="ctrl.notify(notifyMe.email)">
                                    Keep Me Posted
                                </md-button>
                            </div>
                            <div class="success-indicator" style="display: inline-block;">
                                <i class="fa fa-check"
                                   aria-hidden="true"></i>
                            </div>
                        </div>
                    </form>
                </p>
            </div>
        </div>
    </div>
    <div class="footer">
        <div class="container">
            <a href="#">Lumaven</a> <i class="fa fa-copyright copyright"></i> 2016
        </div>
    </div>
</md-content>

src/Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html ng-app="LumavenFrontend">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />

    @if (IsSectionDefined("metatags"))
    {
        @RenderSection("metatags", required: false);
    }
    else
    {
        <meta name="title" content="Lumaven" />
        <meta name="author" content="Dylan Sumiskum" />
        <meta name="description" content="A better way to buy business services. Learn how much your business should really pay for services." />
        <meta name="Keywords" content="lumaven, business services, consulting services, business service marketplace, consulting marketplace, sell business services online, buy business services online, business service pricing" />
    }
    
    <title>Lumaven</title>
	<link rel="shortcut icon" type="image/x-icon" href="~/images/favicon.png" />
	
    <environment names="dev,debug">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <link rel="stylesheet" href="~/lib/angular-material/angular-material.css" />
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Roboto+Condensed:300,400,700|Open+Sans|Open+Sans+Condensed:300|Grand+Hotel" rel="stylesheet">
        <link rel="stylesheet" href="~/css/style.css" />
    </environment>
    <environment names="stg,prd">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <link rel="stylesheet" href="~/lib/angular-material/angular-material.min.css" />
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Roboto+Condensed:300,400,700|Open+Sans|Open+Sans+Condensed:300|Grand+Hotel" rel="stylesheet">
        <link rel="stylesheet" href="~/css/style.min.css" asp-append-version="true" />
    </environment>

    @RenderSection("style", required: false)
</head>
<body layout="row">
    @if (IsSectionDefined("background"))
    {
        @RenderSection("background");
    }
    @if (IsSectionDefined("navbar"))
    {
        @RenderSection("navbar");
    }
    else
    {
        <nav class="navbar navbar-transparent navbar-fixed-top" role="navigation">
            <div class="container">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>

                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav navbar-right">
                    </ul>

                </div><!-- /.navbar-collapse -->
            </div><!-- /.container -->
        </nav>
    }
    
    @RenderBody()
      
    <environment names="dev,debug">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/lib/angular/angular.js"></script>
        <script src="~/lib/angular-animate/angular-animate.js"></script>
        <script src="~/lib/angular-aria/angular-aria.js"></script>
        <script src="~/lib/angular-messages/angular-messages.js"></script>
		<script src="~/lib/angular-material/angular-material.js"></script>
        <script src="~/lib/angular-scroll/angular-scroll.js"></script>
        <script src="~/js/main.js" asp-append-version="true"></script>
    </environment>
    <environment names="stg,prd">
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
        <script src="~/lib/angular/angular.min.js"></script>
        <script src="~/lib/angular-animate/angular-animate.min.js"></script>
        <script src="~/lib/angular-aria/angular-aria.min.js"></script>
        <script src="~/lib/angular-messages/angular-messages.min.js"></script>
		<script src="~/lib/angular-material/angular-material.min.js"></script>
        <script src="~/lib/angular-scroll/angular-scroll.min.js"></script>
        <script src="~/js/main.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>

src/Web/Views/Vendor/Index.cshtml
@{
    var request = ViewContext.HttpContext.Request;
    var routeUrl = Url.RouteUrl(ViewContext.RouteData.Values);
    var thisUrl = $"{request.Scheme}://{request.Host}{routeUrl}";

    var facebookShareUrl = $"http://www.facebook.com/sharer/sharer.php?u={thisUrl}";
}

@section metatags
{
    <meta property="og:url" content="@thisUrl" />
    <meta property="og:type" content="website" />
    <meta property="og:title" content="Information is power" />
    <meta property="og:description" content="Learn how much your business should really pay for services. Find the best vendors. Simple. Sign up for updates, sneak peeks, and special offers as we build a better way to buy business services." />
}

@section navbar
{
    <nav class="navbar navbar-transparent navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="@Url.Action("Index", "Home")"><img src="~/images/logo.small.png" /></a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="@Url.Action("Index", "Vendor")">
                            <i class="fa fa-users" aria-hidden="true"></i>
                            Vendor Application
                        </a>
                    </li>
                    <li>
                        <a href="@facebookShareUrl">
                            <i class="fa fa-facebook-square"></i>
                            Share
                        </a>
                    </li>
                    <li>
                        <a href="mailto:info@lumaven.com">
                            <i class="fa fa-envelope-o"></i>
                            Contact Us
                        </a>
                    </li>
                </ul>

            </div><!-- /.navbar-collapse -->
        </div><!-- /.container -->
    </nav>
}

<div class="background-white-frosted"></div>
<md-content id="surveyContainer"
            ng-controller="VendorController as model"
            ng-cloack
            style="background: none;">
    <!-- Content -->
    <survey config="model.surveyConfig"
            ng-if="model.surveyConfig"
            container-id="surveyContainer"
            on-completed="model.submitVendor(answers)"
            flex="85"
            flex-xs="100"
            layout="column"
            md-scroll-y
            layout-padding
            class="survey-padding">
    </survey>
</md-content>